# Site settings
title: OVO AMP
email: your-email@domain.com
description: >
  This is a Opt-in-Value-Offer Page, running on AMP
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: /blog/page:num/

name: 'Your Name'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id:

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-seo-tag


# Collections
collections:
  testimonials:
    output: true
    permalink: /:collection/:title/
  courses:
    output: true
    permalink: /:collection/:title/

# Reading Files
include:
  - .htaccess
  - _pages

# SEO-Tags
lang: "en_US"
author: Gott50 # default Author
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
## Social Sharing
twitter:
  username:
facebook:
  app_id: # a Facebook app ID for Facebook insights
  publisher: # a Facebook page URL or ID of the publishing entity
  admins: # a Facebook user ID for domain insights linked to a personal account
logo: /assets/images/logo.jpg # Open Graph/Twitter default site image

# For specifying social profiles / SEO-Tags
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://github.com/Gott50

# Defaults
defaults:
  # default
  - scope:
      path: ""
    values:
      image: /assets/images/author.jpg # path of fallback teaser image, e.g. "/assets/images/500x300.png"
  # _courses
  - scope:
      path: ""
      type: courses
    values:
      layout: page
      meta: Course
