# Site settings
title: OVO AMP
email: your-email@domain.com
description: >
  This is a Opt-in-Value-Offer Page, running on AMP
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: /blog/page:num/

name: 'Your Name'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username:  jekyll

# Google Analytics
analytics_id:

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate


# Collections
collections:
  testimonials:
    output: true
    permalink: /:collection/:title/
  tutorials:
    output: true
    permalink: /:collection/:title/

# Reading Files
include:
  - .htaccess
  - _pages